# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20161115_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabilidad',
            name='entrada',
            field=models.IntegerField(default=''),
        ),
    ]
