# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20161115_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabilidad',
            name='entrada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='saldo_general',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='salida',
            field=models.IntegerField(null=True),
        ),
    ]
