# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_auto_20161115_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabilidad',
            name='fecha_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
